// loaders
export const LOGIN_ENABLE_LOADER = "LOGIN_ENABLE_LOADER";
export const LOGIN_DISABLE_LOADER = "LOGIN_DISABLE_LOADER";
export const INVENTORY_ENABLE_LOADER = "INVENTORY_ENABLE_LOADER";
export const INVENTORY_DISABLE_LOADER = "INVENTORY_DISABLE_LOADER";

// login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOG_OUT = "LOG_OUT";

// registration
export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const REGISTRATION_RESPONSE = "REGISTRATION_RESPONSE";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

// inventory
export const INVENTORY_REQUEST = "INVENTORY_REQUEST";
export const INVENTORY_RESPONSE = "INVENTORY_RESPONSE";
export const CLEAR_INVENTORY = "CLEAR_INVENTORY";

export const ADD_ASSET_REQUEST = "ADD_ASSET_REQUEST";
export const ADD_ASSET_RESPONSE = "ADD_ASSET_RESPONSE";
export const ADD_ASSET_FAILED = "ADD_ASSET_FAILED";
