// loaders
export const LOGIN_ENABLE_LOADER = "LOGIN_ENABLE_LOADER";
export const LOGIN_DISABLE_LOADER = "LOGIN_DISABLE_LOADER";
export const INVENTORY_ENABLE_LOADER = "INVENTORY_ENABLE_LOADER";
export const INVENTORY_DISABLE_LOADER = "INVENTORY_DISABLE_LOADER";

// Spring Boot users
export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_RESPONSE = "ALL_USERS_RESPONSE";
export const USER_REQUEST = "USER_REQUEST";
export const USER_RESPONSE = "USER_RESPONSE";
export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_RESPONSE = "ADD_USER_RESPONSE";

// login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOG_OUT = "LOG_OUT";

// registration
export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const REGISTRATION_RESPONSE = "REGISTRATION_RESPONSE";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const CLEAR_REGISTRATION_FLAG = "CLEAR_REGISTRATION_FLAG";

// inventory
export const INVENTORY_REQUEST = "INVENTORY_REQUEST";
export const INVENTORY_RESPONSE = "INVENTORY_RESPONSE";
export const CLEAR_INVENTORY = "CLEAR_INVENTORY";

export const ADD_ASSET_REQUEST = "ADD_ASSET_REQUEST";
export const ADD_ASSET_RESPONSE = "ADD_ASSET_RESPONSE";
export const ADD_ASSET_FAILED = "ADD_ASSET_FAILED";

// Spring Boot assets
export const SB_INVENTORY_REQUEST = "SB_INVENTORY_REQUEST";
export const SB_INVENTORY_RESPONSE = "SB_INVENTORY_RESPONSE";

export const SB_NAME_ASSET_REQUEST = "SB_NAME_ASSET_REQUEST";
export const SB_NAME_ASSET_RESPONSE = "SB_NAME_ASSET_RESPONSE";
export const SB_NUMBER_ASSET_REQUEST = "SB_NUMBER_ASSET_REQUEST";
export const SB_NUMBER_ASSET_RESPONSE = "SB_NUMBER_ASSET_RESPONSE";

export const SB_ADD_ASSET_REQUEST = "SB_ADD_ASSET_REQUEST";
export const SB_ADD_ASSET_RESPONSE = "SB_ADD_ASSET_RESPONSE";
export const SB_ASSIGN_ASSET_TO_USER_REQUEST =
  "SB_ASSIGN_ASSET_TO_USER_REQUEST";
export const SB_ASSIGN_ASSET_TO_USER_RESPONSE =
  "SB_ASSIGN_ASSET_TO_USER_RESPONSE";

export const SB_DELETE_ASSET_BY_ID_REQUEST = "SB_DELETE_ASSET_BY_ID_REQUEST";
export const SB_DELETE_ASSET_BY_ID_RESPONSE = "SB_DELETE_ASSET_BY_ID_RESPONSE";
export const SB_DELETE_ASSET_BY_NUMBER_REQUEST =
  "SB_DELETE_ASSET_BY_NUMBER_REQUEST";
export const SB_DELETE_ASSET_BY_NUMBER_RESPONSE =
  "SB_DELETE_ASSET_BY_NUMBER_RESPONSE";
